runtime: nodejs20
instance_class: F1

handlers:
  - url: /(.*\..+)$  # Serve static files (e.g., .js, .css, .png)
    static_files: dist/\1
    upload: dist/(.*\..+)$

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html



