runtime: nodejs18  # or python38 as a placeholder for static sites
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(css|js|png|jpg|ico|svg|json|txt))$
    static_files: build/\1
    upload: build/(.*\.(css|js|png|jpg|ico|svg|json|txt))$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html
