runtime: nodejs18
instance_class: F1

handlers:
  - url: /static
    static_dir: build/static

  - url: /(.*\.(css|js|png|jpg|ico|svg|json|txt))$
    static_files: build/\1
    upload: build/(.*\.(css|js|png|jpg|ico|svg|json|txt))$

  - url: /.*
    static_files: build/index.html
    upload: build/index.html

automatic_scaling:
  min_instances: 1
  max_instances: 5
